/* Pixel Bet V3 visual/label patch over the existing demo game engine. */
function pixelText(v){return String(v??'').replaceAll('K Coin','Pixel Coin').replaceAll('KC','PC').replaceAll('R$ TEST','R$ TESTE').replaceAll('Velyx','Pixel Bet').replaceAll('VELYX','PIXEL')}
ui=function(){topK.textContent=fmt(S.k);heroK.textContent=fmt(S.k);walletK.textContent=fmt(S.k);aK.textContent=fmt(S.k)+' PC';topR.textContent=money(S.r);heroR.textContent=money(S.r);walletR.textContent=money(S.r);aR.textContent='R$ '+money(S.r);aBets.textContent=S.bets;aWins.textContent=S.wins;const claimed=S.lastClaim===today();dailyStatus.textContent=claimed?'Bônus diário de Pixel Coin já resgatado hoje.':'100 PC disponíveis para resgate hoje.';claimMsg.textContent=claimed?'Você já resgatou os 100 PC de hoje.':'Disponível agora: +100 PC.';hist.innerHTML=S.h.length?S.h.map(x=>`<tr><td>${pixelText(x.e)}</td><td>${pixelText(x.g)}</td><td>${pixelText(x.w)}</td><td>${pixelText(x.v)}</td><td>${pixelText(x.r)}</td><td>${x.d}</td></tr>`).join(''):'<tr><td colspan="6">Nenhuma atividade ainda.</td></tr>'}
gameCards=function(list){return list.map(g=>`<div class="card game" onclick="openGame('${g[0]}')"><div class="ico">${g[2]}</div><strong>${g[1]}</strong><small>Interativo · PC / R$ TESTE</small></div>`).join('')}
claimDaily=function(){if(S.lastClaim===today()){claimMsg.textContent='Você já resgatou hoje.';return}S.k+=100;S.lastClaim=today();log('Bônus diário','Daily','Pixel Coin','+100 PC','Resgatado');save()}
adminAdd=function(){let a=+adminAmt.value;if(!(a>0))return;if(adminWallet.value==='k'){S.k+=a;log('Crédito admin','Admin','Pixel Coin','+'+fmt(a)+' PC','Teste')}else{S.r+=a;log('Crédito admin','Admin','R$ TESTE','+R$ '+money(a),'Teste')}save()}
resetDemo=function(){if(!confirm('Resetar todos os saldos e histórico da Pixel Bet?'))return;S={k:1000,r:0,bets:0,wins:0,h:[],lastClaim:null};save()}
walletLabel=function(w){return w==='k'?'Pixel Coin':'R$ TESTE'}
valueLabel=function(w,a){return w==='k'?fmt(a)+' PC':'R$ '+money(a)}
openPay=function(m){payMethod=m;payPending=0;payTitle.textContent=m+' TEST';payFlow.classList.add('hidden');payProg.style.width='0';payModal.classList.add('on')}
createSandboxPayment=function(){let a=+payAmount.value;if(!(a>0)){alert('Informe um valor válido.');return}payPending=a;payFlow.classList.remove('hidden');payCode.textContent=`PIXEL-${payMethod.toUpperCase()}-TEST-${Date.now()}-${Math.random().toString(36).slice(2,10).toUpperCase()}`;setTimeout(()=>payProg.style.width='100%',30)}
confirmSandboxPayment=function(){if(!(payPending>0))return;S.r+=payPending;log('Pagamento sandbox',payMethod,'R$ TESTE','+R$ '+money(payPending),'Confirmado em teste');save();alert('Pagamento de teste confirmado. Saldo R$ TESTE atualizado.');closePay();payPending=0}
games.innerHTML=gameCards(G);featured.innerHTML=gameCards(G.slice(0,4));ui();